# Copyright: 2011 MoinMoin:ThomasWaldmann
# License: GNU GPL v2 (or any later version), see LICENSE.txt for details.

"""
MoinMoin - fileserver backend tests
"""


from __future__ import absolute_import, division

import os, tempfile

import pytest

from backend.fileserver import Backend
from backend._tests import BackendTestBase


class TestFileServerBackend(BackendTestBase):
    def setup_method(self, method):
        self.path = path = tempfile.mkdtemp()
        self.be = Backend(path)
        self.be.open()

    def test_with_files(self):
        # note: as we can only store the data into the file system, meta can
        # only have items that are generated by the fileserver backend:
        items = [#name,  meta,   data
                 ('foo.png', dict(size=11), 'png content'),
                 ('bar.txt', dict(size=12), 'text content'),
                ]
        expected_result = set()
        for name, meta, data in items:
            fn = os.path.join(self.path, name)
            with open(fn, 'wb') as f:
                f.write(data)
            meta = tuple(sorted(meta.items()))
            expected_result.add((meta, data))
        result = set()
        for i in self.be:
            meta, data = self.be.get_revision(i)
            # we don't want to check mtime
            del meta['mtime']
            meta = tuple(sorted(meta.items()))
            data = data.read()
            result.add((meta, data))
        assert result == expected_result

